name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout project sources
          uses: actions/checkout@v3
      -   name: Set env
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -   name: Setup Gradle
          uses: gradle/gradle-build-action@v2
      -   name: Run build with Gradle Wrapper
          run: gradle build
          env:
            USERNAME: ${{secrets.USERNAME}}
            TOKEN: ${{secrets.TOKEN}}
            RELEASE_VERSION: ${{github.run_number}}


  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build-gradle-project
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/libs/DiscordBot.jar"
